export const RETRIEVE_LATEST = 'RETRIEVE_LATEST';
export const RETRIEVE_LATEST_SUCCESS = 'RETRIEVE_LATEST_SUCCESS';
export const RETRIEVE_LATEST_FAILED = 'RETRIEVE_LATEST_FAILED';

export const RETRIEVE_POPULAR = 'RETRIEVE_POPULAR';
export const RETRIEVE_POPULAR_SUCCESS = 'RETRIEVE_POPULAR_SUCCESS';
export const RETRIEVE_POPULAR_FAILED = 'RETRIEVE_POPULAR_FAILED';

export const RETRIEVE_SEARCH = 'RETRIEVE_SEARCH';
export const RETRIEVE_SEARCH_SUCCESS = 'RETRIEVE_SEARCH_SUCCESS';
export const RETRIEVE_SEARCH_FAILED = 'RETRIEVE_SEARCH_FAILED';
