export const SUBMIT_SIGNUP_REQUESTED = 'SUBMIT_SIGNUP_REQUESTED';
export const SUBMIT_SIGNUP_SUCCESS = 'SUBMIT_SIGNUP_SUCCESS';
export const SUBMIT_SIGNUP_FAILED = 'SUBMIT_SIGNUP_FAILED';

export const CHECK_LOGGEDIN_REQUESTED = 'CHECK_LOGGEDIN_REQUESTED';
export const CHECK_LOGGEDIN_SUCCESSED = 'CHECK_LOGGEDIN_SUCCESSED';
